#!/usr/bin/env bash

# install pywal16 via pip3
sudo xbps-install -Sy python3-pipenv python3-pipx ImageMagick imv

pipx install pywal16

pipx ensurepath
echo " eval "$(register-python-argcomplete pipx)" " >> ~/.bashrc

source ~/.bashrc



# install walbox theme for openbox
git clone https://github.com/edisile/walbox.git
# copy install.sh because fault in script
cp install.sh walbox/.
cd walbox
./install.sh
cd ..


rm -rf .git


# copy several config files
cp -Rv ~/dotfiles/pywal16/.config/* ~/.config

# copy script for changing wallpaper, because wal runs in pip sandbox
cp -v ~/dotfiles/pywal16/chwal.sh ~/.local/bin/.


# create dirs for geany and pywal
mkdir -p ~/.config/geany/colorschemes ~/.config/wal/templates

# create template for geany in pywal16

cat > ~/.config/wal/templates/geany.conf <<'EOF'
[theme_info]
name=Pywal16
description=Generated by pywal16
version=1

[named_colors]
foreground={color7}
background={color0}
selection={color2}
current_line={color8}
comment={color8}
keyword={color4}
string={color6}
number={color5}
type={color3}
error={color9}

[named_styles]
default=foreground;background;false;false
selection=foreground;selection;false;true
current_line=foreground;current_line;false;false
comment=comment;background;false;false
number=number;background;false;false
type=type;background;false;false
keyword=keyword;background;true;false
string=string;background;false;false
function=foreground;background;false;false
identifier=default
operator=keyword
preprocessor=type
other=default

EOF



source ~/.bashrc

# which wal
~/.local/bin/wal -v

~/.local/bin/chwal.sh  ~/.wallpaper/blue-mountains.jpg
# create symbol link to pywall.16.conf, select in geany this theme
# Menu -> View -> change color schema : select pywal16

ln -sf ~/.cache/wal/geany.conf  ~/.config/geany/colorschemes/Pywal16.conf

# works only in Xwindows not in console
# openbox --reconfigure

