#!/usr/bin/env bash

# install pywal16 via pip3
sudo xbps-install -Sy python3-pipenv python3-pipx ImageMagick imv

pipx install pywal16

pipx ensurepath
echo " eval "$(register-python-argcomplete pipx)" " >> ~/.bashrc

source ~/.bashrc



# install walbox theme for openbox
git clone https://github.com/edisile/walbox.git
# copy install.sh because fault in script
cp install.sh walbox/.
cd walbox
./install.sh
cd ..


rm -rf .git
rm -rf walbox

# copy several config files
cp -Rv ~/dotfiles/pywal16/.config/* ~/.config

# copy script for changing wallpaper, because wal runs in pip sandbox
cp -v ~/dotfiles/pywal16/chwal.sh ~/.local/bin/.


# create dirs for geany and pywal
mkdir -p ~/.config/geany/colorschemes ~/.config/wal/templates

# create template for geany in pywal16

cat > ~/.config/wal/templates/geany.conf <<'EOF'
#
# Geany color scheme generated by pywal16
# https://github.com/eylles/pywal16
#
# Install this file as a pywal16 template:
#   ~/.config/wal/templates/geany.conf
#
# After running `wal`, symlink the generated output into Geany's
# colorschemes directory so it updates automatically each time you
# change your wallpaper/colors:
#
#   mkdir -p ~/.config/geany/colorschemes
#   ln -sf ~/.cache/wal/geany.conf ~/.config/geany/colorschemes/pywal16.conf
#
# Then in Geany: View > Editor > Color Schemes > Pywal16
#

[theme_info]
name=Pywal16
description=Generated by pywal16 from the current color scheme
version=1.0
author=pywal16
compat=1.24

[named_styles]

default={foreground};{background};false;false
error={color1};{background};true;italic

# Editor styles
#-------------------------------------------------------------------------------

selection=;{color8};false;true
current_line={foreground};{color0};true
brace_good={color2};{background};true;false
brace_bad={color1};{background};true;false
margin_line_number={color8};{background}
margin_folding={color8};{color0}
fold_symbol_highlight={color0}
indent_guide={color8};{background};false;false
caret={foreground};{background};false;false
marker_line={color8};{color0}
marker_search=;{color3}
marker_mark={color8};{color0}
call_tips=default
white_space={color8};{background};true;false

# Generic programming languages
#-------------------------------------------------------------------------------

comment={color8}
comment_doc={color8}
comment_line=comment
comment_line_doc=comment_doc
comment_doc_keyword=comment_doc,bold
comment_doc_keyword_error=comment_doc,italic

number={color5}
number_1=number
number_2=number_1

type={color3};;true
class=type
function={color4}
parameter={color6}

keyword={color5};;true
keyword_1=keyword
keyword_2={color4};;true
keyword_3=keyword_1
keyword_4=keyword_1

identifier=default
identifier_1=identifier
identifier_2={color6}
identifier_3=identifier_1
identifier_4=identifier_1

string={color2}
string_1=string
string_2=string_1
string_3=default
string_4=default
string_eol=string_1,italic
character=string_1
backticks=string_2
here_doc=string_2

scalar=string_2
label=default,bold
preprocessor={color5}
regex=number_1
operator={foreground}
decorator=string_1,bold
other=default

# Markup-type languages
#-------------------------------------------------------------------------------

tag=type
tag_unknown=tag,bold
tag_end=tag,bold
attribute=keyword_1
attribute_unknown=attribute,bold
value=string_1
entity=default

# Diff
#-------------------------------------------------------------------------------

line_added={foreground};{color2}
line_removed={foreground};{color1}
line_changed={foreground};{color3}
EOF



source ~/.bashrc

# which wal
~/.local/bin/wal -v

~/.local/bin/chwal.sh  ~/.wallpaper/blue-mountains.jpg
# create symbol link to pywall.16.conf, select in geany this theme
# Menu -> View -> change color schema : select pywal16

ln -sf ~/.cache/wal/geany.conf  ~/.config/geany/colorschemes/pywal16.conf

# works only in Xwindows not in console
# openbox --reconfigure

