[General]
__userfile__=true
backlightIdleness=0
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=false
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessBacklightWatcher=false
enableIdlenessWatcher=true
enableLidWatcher=false
hibernateKeyAction=1
iconType=1
idlenessACAction=-1
idlenessACTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessBatteryAction=-1
idlenessBatteryTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessTime=@Variant(\0\0\0\xf\0\0\x3\xe8)
lidClosedAcAction=4
lidClosedAction=4
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
monitorIdlenessACTime=@Variant(\0\0\0\xf\0\0\xea`)
monitorIdlenessBatteryTime=@Variant(\0\0\0\xf\0\0\xea`)
powerKeyAction=3
powerLowAction=-1
powerLowLevel=5
powerLowWarning=30
runCheckLevel=1
showIcon=true
suspendKeyAction=4
