
#!/usr/bin/bash
# install superfile -with pywal16 color theme
# url : https://superfile.dev/
# script to install superfile with pywal color scheme


# install superfile (spf), will be installed in /usr/local/bin/
bash -c "$(wget -qO- https://superfile.dev/install.sh)"

# template dir in pywal16
mkdir -p ~/.config/wal/templates/

# create superfile template file
cat <<EOF > ~/.config/wal/templates/superfile-theme.toml

# Generated by pywal
# Superfile Theme

# ========= Border =========
file_panel_border = '{color8}'
sidebar_border = '{background}'
footer_border = '{color8}'

# ========= Border Active =========
file_panel_border_active = '{color4}'
sidebar_border_active = '{color1}'
footer_border_active = '{color2}'
modal_border_active = '{color7}'

# ========= Background (bg) =========
full_screen_bg = '{background}'
file_panel_bg = '{background}'
sidebar_bg = '{background}'
footer_bg = '{background}'
modal_bg = '{background}'

# ========= Foreground (fg) =========
full_screen_fg = '{foreground}'
file_panel_fg = '{foreground}'
sidebar_fg = '{foreground}'
footer_fg = '{foreground}'
modal_fg = '{foreground}'

# ========= Special Color =========
cursor = '{cursor}'
correct = '{color2}'
error = '{color1}'
hint = '{color4}'
cancel = '{color5}'
gradient_color = ['{color4}', '{color6}']

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '{color2}'
file_panel_top_path = '{color4}'
file_panel_item_selected_fg = '{color4}'
file_panel_item_selected_bg = '{background}'

# ========= Sidebar Special Items =========
sidebar_title = '{color4}'
sidebar_item_selected_fg = '{color4}'
sidebar_item_selected_bg = '{background}'
sidebar_divider = '{color7}'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '{color5}'
modal_confirm_fg = "#383838"
modal_confirm_bg = '{color6}'
EOF


# create dummy-file
touch $HOME/.cache/wal/superfile-theme.toml

# mkdir -p $HOME/.config/superfile/theme
# config standard file config file, because there not created by  superfile yet
cp -r $HOME/dot-files/scripts/superfile/ $HOME/.config/


# create symbolic in from the pywall cache dir to superfile theme dir
ln -sf $HOME/.cache/wal/superfile-theme.toml $HOME/.config/superfile/theme/pywal.toml


# Change theme in ./config/superfile/config.toml
awk '
/^theme[[:space:]]*=[[:space:]]*"pywal"/ {
  print
  next
}
/^theme[[:space:]]*=/ {
  print "#" $0
  print "theme = \"pywal\""
  next
}
{ print }
' ~/.config/superfile/config.toml > /tmp/config.toml.tmp \
&& mv /tmp/config.toml.tmp ~/.config/superfile/config.toml
